package models

data class Card(
    val archived: Boolean,
    val asap: Boolean,
    val blocked: Boolean,
    val blocking_card: Boolean,
    var board_id: Int,
    val sprint_id: Any,
    val state: Int,
    val title: String,
    val column_changed_at: String,
    var column_id: Int,
    val created: String,
    var lane_id: Int,
    val description_filled: Boolean,
    val id: Int,
    var due_date: String?,
//    val due_date_time_present: Boolean,
//    val calculated_planned_end: Any,
//    val calculated_planned_start: Any,
//    val children_count: Int,
//    val children_done: Int,
//    val children_ids: Any,
//    val children_number_properties_sum: Any,
//    val comment_last_added_at: Any,
//    val comments_total: Int,
//    val completed_at: Any,
//    val completed_on_time: Any,
//    val condition: Int,
//    val counters_recalculated_at: String,
//    val estimate_workload: Int,
//    val expires_later: Boolean,
//    val external_id: Any,
//    val external_user_emails: Any,
//    val fifo_order: Any,
//    val first_moved_to_in_progress_at: String,
//    val goals_done: Int,
//    val goals_total: Int,
//    val has_blocked_children: Boolean,
//    val lane_changed_at: String,
//    val last_moved_at: String,
//    val last_moved_to_done_at: String,
//    val members: List<Member>,
//    val owner: Owner,
//    val owner_id: Int,
//    val parent_checklist_ids: Any,
//    val parents_count: Int,
//    val parents_ids: Any,
//    val planned_end: Any,
//    val planned_start: Any,
//    val properties: Any,
//    val `public`: Boolean,
//    val sd_new_comment: Boolean,
//    val service_id: Any,
//    val share_id: Any,
//    val share_settings: Any,
//    val size: Any,
//    val size_text: Any,
//    val size_unit: Any,
//    val sort_order: Double,
//    val time_blocked_sum: Int,
//    val time_spent_sum: Int,
//    val type: Type,
//    val type_id: Int,
//    val updated: String,
//    val updater_id: Int,
//    val version: Int
)